<?php

namespace NetteAddons;

final class RedirectPresenter extends \Nette\Application\UI\Presenter
{
	const NEW_PORTAL_URL_MASK = 'https://componette.com/%s/';

	/** @var string[] */
	private $map;


	public function __construct()
	{
		parent::__construct();

		$this->map = [
			'peci1/suggestinput' => 'peci1/nette-suggestinput',
			'smasty/twitter-control' => 'smasty/twittercontrol',
			'foowie/dependentselectbox' => 'foowie/dependentselectbox',
			'lohini/framework' => 'lohini/framework',
			'mikulas-dite/navigationpanel' => 'mikulas/nette-plugins-navigationpanel',
			'jkuchar/pdfresponse' => 'jkuchar/pdfresponse',
			'hostbox/nette-paypal-payment-buttons' => 'hostbox/nette-paypal-payment-buttons',
			'rm/header' => 'romanmatyus/header',
			'vojtech-dobes/nette-goto-panel' => 'vojtech-dobes/nette-goto-panel',
			'jkuchar/multiplefileupload' => 'jkuchar/multiplefileupload',
			'vojtech-dobes/composer-extension' => 'vojtech-dobes/nette-composer-extension',
			'sodae/netrium-addons-twitter' => 'martinsadovy/netrium-addons-twitter',
			'bazo/nette-neo4j-extension' => 'bazo/nette-neo4j-extension',
			'nextras/datagrid' => 'nextras/datagrid',
			'olicek/google-map-api' => 'olicek/googlemapapi',
			'nella/forms-phone' => 'nella/forms-phone',
			'milo/xdebug-trace-panel' => 'milo/xdebugtracepanel',
			'vladahejda/livetranslator' => 'vladahejda/livetranslator',
			'uestla/http-auth-extension' => 'uestla/httpauthextension',
			'markette/gopay' => 'markette/gopay',
			'vojtech-dobes/nette-multi-authenticator' => 'vojtech-dobes/nette-multi-authenticator',
			'trunda/smf-menu' => 'trunda/smfmenu',
			'h4kuna/gettext-latte' => 'h4kuna/gettext-latte',
			'h4kuna/fio' => 'h4kuna/fio',
			'rm/filemailer' => 'romanmatyus/filemailer',
			'viliamkopecky/nette-ristretto' => 'viliamkopecky/netteristretto',
			'rhrebecek/googlemapsimage' => 'rhrebecek/googlemapsimage',
			'h4kuna/exchange' => 'h4kuna/exchange',
			'vojtech-dobes/nette-forms-gpspicker' => 'vojtech-dobes/nette-forms-gpspicker',
			'zeleznypa/nette-button-macros' => 'zeleznypa/nette-button-macros',
			'zeleznypa/nette-session-debug-bar' => 'zeleznypa/nette-session-debug-bar',
			'janmarek/webloader' => 'janmarek/webloader',
			'kdyby/doctrine-cache' => 'kdyby/doctrinecache',
			'kdyby/annotations' => 'kdyby/annotations',
			'greeny/maillibrary' => 'greeny/maillibrary',
			'o5/grido' => 'o5/grido',
			'illagrenan/nette-facebook-connect' => 'illagrenan/nette-facebook-connect',
			'mikulas/nette-google-oauth2' => 'mikulas/nette-google-oauth2',
			'vojtech-dobes/extensions-list' => 'vojtech-dobes/nette-extensions-list',
			'jsmitka/nette-xdebug-helper' => 'jsmitka/nette-xdebug-helper',
			'foglcz/jsonrpc2' => 'foglcz/jsonrpc2',
			'echo511/plupload' => 'echo511/plupload',
			'voda/date-input' => 'voda/dateinput',
			'jkuchar/bigfiletools' => 'jkuchar/bigfiletools',
			'jasir/component-tree-panel' => 'jasir/componenttreepanel',
			'voda/php-translator' => 'voda/php-translator',
			'jasir/phpedpanel' => 'jasir/phpedpanel',
			'foowie/presenterlinkpanel' => 'foowie/presenterlinkpanel',
			'kdyby/bootstrap-form-renderer' => 'kdyby/bootstrapformrenderer',
			'kdyby/forms-replicator' => 'kdyby/replicator',
			'kdyby/curl' => 'kdyby/curl',
			'kdyby/console' => 'kdyby/console',
			'kdyby/doctrine' => 'kdyby/doctrine',
			'kdyby/redis' => 'kdyby/redis',
			'kdyby/autowired' => 'kdyby/autowired',
			'kdyby/facebook' => 'kdyby/facebook',
			'kdyby/events' => 'kdyby/events',
			'kdyby/translation' => 'kdyby/translation',
			'michalsvec/nette-opauth' => 'michalsvec/nette-opauth',
			'kdyby/money' => 'kdyby/money',
			'stekycz/cronner' => 'stekycz/cronner',
			'kdyby/doctrine-money' => 'kdyby/doctrinemoney',
			'venne/packages' => 'venne/packages',
			'brabijan/images' => 'brabijan/images',
			'vojtech-dobes/nette-signals-trait' => 'vojtech-dobes/nette-signals-trait',
			'radekdostal/nette-datetimepicker' => 'radekdostal/nette-datetimepicker',
			'radekdostal/nette-imageselectbox' => 'radekdostal/nette-imageselectbox',
			'ipub/gravatar' => 'ipublikuj/gravatar',
			'kdyby/github' => 'kdyby/github',
			'kdyby/google' => 'kdyby/google',
			'uestla/twigrid' => 'uestla/twigrid',
			'krejcon3/checkboxtree' => 'krejcon3/checkboxtree',
			'milo/github-api-nette' => 'milo/github-api-nette',
			'kdyby/monolog' => 'kdyby/monolog',
			'foglcz/ldap-authenticator' => 'foglcz/ldap-authenticator',
			'nella/forms-datetime' => 'nella/forms-datetime',
			'zenify/flash-message-component' => 'zenify/flashmessagecomponent',
			'zenify/title-component' => 'zenify/titlecomponent',
			'zenify/doctrine-behaviors' => 'zenify/doctrinebehaviors',
			'nasext/sorting-control' => 'nasext/sortingcontrol',
			'nasext/items-per-page' => 'nasext/itemsperpage',
			'brabijan/nette-seo-components' => 'brabijan/nette-seo-components',
			'majkl578/nette-identity-doctrine' => 'majkl578/nette-identity-doctrine',
			'majkl578/nette-injects-extension' => 'majkl578/nette-injects-extension',
			'vrtak-cz/newrelic-tracy' => 'vrtak-cz/newrelic-tracy',
			'vrtak-cz/newrelic-nette' => 'vrtak-cz/newrelic-nette',
			'kdyby/rabbitmq' => 'kdyby/rabbitmq',
			'jkuchar/filedownloader' => 'jkuchar/filedownloader',
			'lawondyss/cdnloader' => 'lawondyss/cdnloader',
			'janpecha/leanmapper-extension' => 'janpecha/leanmapper-extension',
			'zenify/doctrine-migrations' => 'zenify/doctrinemigrations',
			'zenify/doctrine-methods-hydrator' => 'zenify/doctrinemethodshydrator',
			'zenify/doctrine-filters' => 'zenify/doctrinefilters',
			'zenify/doctrine-fixtures' => 'zenify/doctrinefixtures',
			'nextras/static-router' => 'nextras/static-router',
			'nextras/link-factory' => 'nextras/link-factory',
			'nella/simple-hash-authenticator' => 'nella/simple-hash-authenticator',
			'ondrs/hi' => 'ondrs/hi',
			'ondrs/upload-manager' => 'ondrs/upload-manager',
			'bauer01/fake-login' => 'bauer01/fake-login',
			'olicek/form-selectize' => 'olicek/form-selectize',
			'ipub/permissions' => 'ipublikuj/permissions',
			'hostbox/api-payu-nette-bridge' => 'hostbox/api-payu-nette-bridge',
			'meridius/yadup' => 'meridius/yadup',
			'nella/forms-signal-control' => 'nella/forms-signal-control',
			'nedryse/latte-template-macroset' => 'nedryse/latte-template-macroset',
			'webchemistry/images' => 'webchemistry/images',
			'carrooi/security' => 'carrooi/nette-security',
			'carrooi/assets' => 'carrooi/nette-assets',
			'carrooi/cloner' => 'carrooi/nette-cloner',
			'carrooi/favorites' => 'carrooi/nette-favorites',
			'ipub/form-slug' => 'ipublikuj/form-slug',
			'ipub/form-datetime' => 'ipublikuj/form-datetime',
			'ipub/mobile-detect' => 'ipublikuj/mobile-detect',
			'ipub/assets-loader' => 'ipublikuj/assets-loader',
			'carrooi/addressable' => 'carrooi/nette-addressable',
			'carrooi/labels' => 'carrooi/nette-labels',
			'alnux/nette-breadcrumb' => 'alnux/nette-breadcrumb',
			'dotblue/nette-webimages' => 'dotblue/nette-webimages',
			'minetro/recaptcha' => 'minetro/recaptcha',
			'ipub/flickr' => 'ipublikuj/flickr',
			'ipub/twitter' => 'ipublikuj/twitter',
			'ipub/confirmation-dialog' => 'ipublikuj/confirmation-dialog',
			'ipub/visual-paginator' => 'ipublikuj/visual-paginator',
			'ipub/images' => 'ipublikuj/images',
			'ipub/flash-messages' => 'ipublikuj/flash-messages',
			'juniwalk/shield' => 'juniwalk/shield',
			'minetro/latte-email' => 'minetro/latte-email',
			'minetro/mobilni-platby' => 'minetro/mobilni-platby',
			'minetro/events' => 'minetro/events',
			'minetro/thumbator' => 'minetro/thumbator',
			'minetro/social' => 'minetro/social',
			'minetro/forms' => 'minetro/forms',
			'minetro/imap' => 'minetro/imap',
			'wodcz/nette-honeypot' => 'wodcz/nettehoneypot',
			'kollarovic/admin' => 'kollarovic/admin',
			'zemistr/l10n-nette-translator' => 'zemistr/l10n-nette-translator',
			'minetro/cli-http-extension' => 'minetro/cli-http-extension',
			'kollarovic/shopping-cart' => 'kollarovic/shoppingcart',
			'minetro/latte-parsedown' => 'minetro/latte-parsedown',
			'minetro/latte-parsedown-extra' => 'minetro/latte-parsedown-extra',
			'kdyby/elastic-search' => 'kdyby/elasticsearch',
			'kdyby/wkhtmltopdf' => 'kdyby/wkhtmltopdf',
			'kdyby/fake-session' => 'kdyby/fakesession',
			'minetro/deployer-extension' => 'minetro/deployer-extension',
			'fakerino/nette-fakerino' => 'fakerino/nette-fakerino',
			'carrooi/nette-menu' => 'carrooi/nette-menu',
			'vaclav-sir/n-browser-kit' => 'vaclavsir/nbrowserkit',
			'webchemistry/forms' => 'webchemistry/forms',
			'webchemistry/forms-controls' => 'webchemistry/forms-controls',
			'webchemistry/forms-multiplier' => 'webchemistry/forms-multiplier',
			'webchemistry/forms-doctrine' => 'webchemistry/forms-doctrine',
			'sunfoxcz/date-utils' => 'sunfoxcz/date-utils',
			'sunfoxcz/price-calculator' => 'sunfoxcz/price-calculator',
			'metisfw/paypal' => 'metisfw/paypal',
			'lookyman/recaptcha' => 'lookyman/recaptcha',
			'lookyman/pratchett' => 'lookyman/pratchett',
			'lookyman/mandrill' => 'lookyman/mandrill',
			'macfja/tracy-doctrine-sql' => 'macfja/tracy-doctrine-sql',
			'mrtnzlml/testbench' => 'mrtnzlml/testbench',
			'nasext/dependent-select-box' => 'nasext/dependentselectbox',
			'machy8/macdom' => 'machy8/macdom',
			'uestla/yetorm' => 'uestla/yetorm',
			'blitzik/calendar' => 'blitzik/calendar',
			'uestla/recaptcha-control' => 'uestla/recaptchacontrol',
			'ublaboo/mailing' => 'ublaboo/mailing',
			'ublaboo/simple-http-auth' => 'ublaboo/simple-http-auth',
			'ublaboo/directory-register' => 'ublaboo/directory-register',
			'ublaboo/controls' => 'ublaboo/controls',
			'webchemistry/parameters' => 'webchemistry/parameters',
			'ublaboo/presenter-component' => 'ublaboo/presenter-component',
			'tomaj/nette-api' => 'tomaj/nette-api',
			'tomaj/nette-bootstrap-form' => 'tomaj/nette-bootstrap-form',
			'milo/vendor-versions' => 'milo/vendor-versions',
			'myiyk/seo-router' => 'myiyk/seo-router',
			'webchemistry/invoice' => 'webchemistry/invoice',
			'premekkoch/pkpaginator' => 'premekkoch/pkpaginator',
			'jzechy/nette-antispam' => 'jzechy/nette-antispam',
			'jzechy/jquery-fileupload' => 'jzechy/jquery-fileupload',
			'hostbox/nette-component-social-plugins' => 'hostbox/nette-social-plugins',
			'lukaj/nette-param-validator' => 'lukasmazur/nette-paramvalidator',
			'zeleznypa/nette-simple-translator' => 'nedryse/simple-translator',
			'kollarovic/thumbnail' => 'kollarovic/thumbnailhelper',
			'jaroslav-kubicek/event-calendar' => 'jaroslav-kubicek/eventcalendar',
			'nifty/nifty-grid' => 'holubj/niftygrid',
			'ondrejbrejla/eciovni' => 'obrejla/eciovni',
			'jandrabek/nette-mailpanel' => 'repli2dev/nette-mailpanel',
			'docx/confirmationdialog' => 'srigi/nette-confirmationdialog',
			'vojtech-dobes/nette-ajax-history' => 'vojtech-dobes/history.nette.ajax.js',
			'sakren/nette-menu' => 'carrooi/nette-menu',
			'flame/modules' => 'flame-org/modules',
			'george-oakling/googlemap' => 'george-oakling/googlemap',
			'zenify/doctrine-identity-entity' => 'zenify/doctrinemigrations',
			'pd/database-info-panel' => 'peckadesign/database-info-panel',
			'jandrabek/tracy-gitversion-panel' => 'repli2dev/tracy-gitversion-panel',
			'annotate/packages' => 'annotateframework/packages',
			'skautis/skautis' => 'skaut/skautisnette',
			'seberm/paypal-component' => 'seberm/nette-paypal',
			'skautis/nette' => 'skaut/skautisnette',
			'minetro/formatter' => 'minetro/latte-formatter',
			'carrooi/images-manager' => 'carrooi/nette-imagesmanager',
			'divisions/nette-propel2-extension' => 'divisions-etch/nette-propel2-extension',
			'divisions/nette-spot2-extension' => 'divisions-etch/nette-spot2-extension',
			'adamstipak/nette-rest-route' => 'newpope/nette-restroute',
			'carrooi/no-grid' => 'carrooi/nette-nogrid',
			'webchemistry/forms-wizard' => 'webchemistry/wizard',
			'webchemistry/rollbar' => 'webchemistry/rollbar',
			'sandbox/passwordrecovery' => 'vipercz/passwordrecovery',
			'makr/feed' => 'martinknor/feed',
			'pavlista/nette-palette' => 'michaelpavlista/nette-palette',
		];
	}


	/**
	 * @param string
	 */
	public function actionDefault($slug)
	{
		$slug = strtolower($slug);

		if (isset($this->map[$slug])) {
			$this->redirectUrl(sprintf(self::NEW_PORTAL_URL_MASK, $this->map[$slug]));
		}

		$this->error('Addon not found', 404);
	}
}
